### ISSUE TITLE
Payment gateway

### ISSUE THREAD

**Issue by mbnoimi** [uasoft-indonesia/badaso-commerce-module#29]
What are the supported payment gateways (providers)?
Do you support [Omnipay](https://github.com/thephpleague/omnipay)?

**Comment by rizkiheryandi** [comment]
badaso support all providers

but available module is for midtrans for now https://github.com/uasoft-indonesia/badaso-midtrans-module

omnipay is also interesting package, it's already has many existing payment gateway, we will looking for that to integrate with badaso soon

you can also help us to integrate it with badaso
