### ISSUE TITLE
Change product description input from text area to WYSIWYG

### ISSUE THREAD

**Issue by rizkiheryandi** [uasoft-indonesia/badaso-commerce-module#34]
![image](https://user-images.githubusercontent.com/25028868/212471706-12ba7376-d2e8-4c35-8945-ca6aee26dd4a.png)

**Comment by billalxcode** [comment]
Hi Badaso developers, what is the meaning of this issue? Is the input position incorrect?

**Comment by rizkiheryandi** [comment]
> Hi Badaso developers, what is the meaning of this issue? Is the input position incorrect?

this issue for enhancement the input from texarea to WYSIWYG

and already merged to the main branch, will release soon
